---
# handlers file for deploy-artifact
#
#
- name: stop tomcat
  service:
    name: tomcat
    state: stopped

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
    
  
