---
# Tasks to perform on a RedHat machine

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install maven
  yum:
    name: maven
    state: present

- name: Clone the repository
  git:
    repo: "{{ git_url }}"
    dest: "{{ repo_dir }}"
    version: "{{ git_branch }}"
  register: source_code_clones

- debug:
    var: source_code_clones.changed

- name: Build code
  shell:
    cmd: mvn clean install
    chdir: "{{ repo_dir }}/"
  when: source_code_clones.changed

